const http = require("http");
const fs = require("fs");
const path = require("path");
const WebSocket = require("ws");
const root = path.join(__dirname, "..", "client");
const server = http.createServer((req, res) => { const file = path.join(root, req.url === "/" ? "index.html" : req.url); if (!file.startsWith(root) || !fs.existsSync(file)) { res.writeHead(404); res.end(); return; } res.writeHead(200, { "Content-Type": file.endsWith(".css") ? "text/css; charset=utf-8" : "text/html; charset=utf-8" }); fs.createReadStream(file).pipe(res); });
const wss = new WebSocket.Server({ server }); const players = new Map();
const values = { "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, J: 11, Q: 12, K: 13, A: 14, "2": 15, "3": 16 }; const order = { "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, J: 11, Q: 12, K: 13, A: 14, "2": 15, "3": 16, "小王": 17, "大王": 18 }; const suits = ["♠", "♥", "♦", "♣"];
let game = reset(); function reset() { return { phase: "waiting", ready: new Set(), hands: new Map(), sheath: [], sheathOwner: 0, turn: 1, lastPlay: null, passCount: 0 }; }
function send(socket, data) { socket.send(JSON.stringify(data)); } function sortHand(hand) { return hand.sort((a, b) => order[a.rank] - order[b.rank]); } function deck() { return [...suits.flatMap((suit) => Object.keys(values).map((rank) => ({ suit, rank }))), { suit: "", rank: "小王", joker: true }, { suit: "", rank: "大王", joker: true }]; }
function broadcast() { const data = { type: "state", count: players.size, phase: game.phase, ready: [...game.ready], turn: game.turn, sheath: game.sheath, sheathOwner: game.sheathOwner, lastPlay: game.lastPlay, players: [...players.values()].map((n) => ({ player: n, cards: game.hands.get(n)?.length || 0 })) }; for (const socket of players.keys()) send(socket, data); }
function give(socket, number) { send(socket, { type: "hand", cards: game.hands.get(number) || [] }); }
function startDeal() { const cards = deck().sort(() => Math.random() - 0.5); game.phase = "sword-choice"; game.sheath = cards.splice(0, 3); game.hands = new Map([[1, []], [2, []], [3, []]]); cards.forEach((card, i) => game.hands.get(i % 3 + 1).push(card)); for (const hand of game.hands.values()) sortHand(hand); game.sheathOwner = [...game.hands].find(([, hand]) => hand.some((card) => card.suit === "♥" && card.rank === "4"))?.[0] || 1; game.turn = game.sheathOwner; for (const [socket, number] of players) { send(socket, { type: "started" }); give(socket, number); } broadcast(); }
function finishSword(number) { game.phase = "playing"; game.hands.get(number).push(...game.sheath); sortHand(game.hands.get(number)); game.sheath = []; game.turn = number; broadcast(); for (const [socket, owner] of players) give(socket, owner); }
function classify(cards) { const v = cards.map((c) => values[c.chosenRank || c.rank]).sort((a, b) => a - b); const same = v.every((x) => x === v[0]); if (cards.length === 4 && same) return { type: "star", label: "星", level: 5, value: v[0] }; if (cards.length === 3 && v.join(",") === "4,4,14") return { type: "pierce", label: "穿剑", level: 4, value: 14 }; if (cards.length === 3 && same && v[0] === 12) return { type: "cannon", label: "大炮", level: 3, value: 12 }; if (cards.length === 3 && same && v[0] === 6) return { type: "smallCannon", label: "小炮", level: 2, value: 6 }; if (cards.length === 3 && same) return { type: "triple", label: "三张", level: 1, value: v[0] }; if (cards.length === 2 && same) return { type: "pair", label: "对子", level: 1, value: v[0] }; if (cards.length >= 3 && !v.some((x) => x < 4) && v.every((x, i) => i === 0 || x === v[i - 1] + 1)) return { type: `straight${cards.length}`, label: `${cards.length}张顺子`, level: 1, value: v.at(-1) }; if (cards.length === 1) return { type: "single", label: "单张", level: 1, value: v[0] }; return null; }
function canBeat(old, next) { return !old || next.level > old.level || next.level === old.level && next.type === old.type && next.value > old.value; }
wss.on("connection", (socket) => { if (players.size >= 3) { send(socket, { type: "full" }); socket.close(); return; } const number = players.size + 1; players.set(socket, number); send(socket, { type: "welcome", player: number }); broadcast(); socket.on("message", (raw) => { let msg; try { msg = JSON.parse(raw); } catch { return; } if (msg.type === "ready" && game.phase === "waiting") { game.ready.add(number); broadcast(); if (players.size === 3 && game.ready.size === 3) startDeal(); return; } if (msg.type === "sword" && game.phase === "sword-choice" && number === game.turn) { if (msg.accept) finishSword(number); else { game.ready.add(number); const next = [1, 2, 3].find((n) => n !== number && !game.ready.has(n)); if (next) game.turn = next; else finishSword(game.sheathOwner); broadcast(); } return; } if (msg.type === "pass" && game.phase === "playing" && number === game.turn) { game.passCount += 1; game.turn = number % 3 + 1; if (game.passCount >= 2) { game.lastPlay = null; game.passCount = 0; } broadcast(); return; } if (msg.type !== "play" || game.phase !== "playing" || number !== game.turn) return; const hand = game.hands.get(number); const indexes = [...new Set(msg.indexes || [])].sort((a, b) => a - b); if (!indexes.length || indexes.some((i) => !hand[i])) return; const selected = indexes.map((i) => ({ ...hand[i] })); if (selected.some((c) => c.joker)) { if (!msg.jokerRank) return; selected.forEach((c) => { if (c.joker) c.chosenRank = msg.jokerRank; }); } const combo = classify(selected); if (!combo || !canBeat(game.lastPlay?.combo, combo)) return; indexes.reverse().forEach((i) => hand.splice(i, 1)); game.lastPlay = { player: number, cards: selected, combo }; game.passCount = 0; game.turn = number % 3 + 1; sortHand(hand); broadcast(); for (const [client, owner] of players) give(client, owner); if (!hand.length) for (const client of players.keys()) send(client, { type: "winner", player: number }); }); socket.on("close", () => { players.delete(socket); game = reset(); broadcast(); }); });
server.listen(Number(process.env.PORT) || 3000, "0.0.0.0", () => console.log("Card game server running"));
