const http = require("http");
const fs = require("fs");
const path = require("path");
const WebSocket = require("ws");
const root = path.join(__dirname, "..", "client");
const server = http.createServer((req, res) => { const file = path.join(root, req.url === "/" ? "index.html" : req.url); if (!file.startsWith(root) || !fs.existsSync(file)) { res.writeHead(404); res.end(); return; } res.writeHead(200, { "Content-Type": file.endsWith(".css") ? "text/css; charset=utf-8" : "text/html; charset=utf-8" }); fs.createReadStream(file).pipe(res); });
const wss = new WebSocket.Server({ server }); const players = new Map(); const ranks = { "2": 2, "3": 3, "4": 4, "5": 5, "6": 6, "7": 7, "8": 8, "9": 9, "10": 10, J: 11, Q: 12, K: 13, A: 14 }; const suits = ["♠", "♥", "♦", "♣"];
let game = { phase: "waiting", ready: new Set(), hands: new Map(), sheath: [], sheathOwner: 0, turn: 1, lastPlay: null };
const reset = () => { game = { phase: "waiting", ready: new Set(), hands: new Map(), sheath: [], sheathOwner: 0, turn: 1, lastPlay: null }; };
function deck() { return [...suits.flatMap((suit) => Object.keys(ranks).map((rank) => ({ suit, rank }))), { suit: "", rank: "小王", joker: true }, { suit: "", rank: "大王", joker: true }]; }
function sortHand(hand) { return hand.sort((a, b) => (a.joker ? 100 : ranks[a.rank]) - (b.joker ? 100 : ranks[b.rank])); }
function send(socket, data) { socket.send(JSON.stringify(data)); } function broadcast() { const data = { type: "state", count: players.size, phase: game.phase, ready: [...game.ready], turn: game.turn, sheath: game.sheath, sheathOwner: game.sheathOwner, players: [...players.values()].map((n) => ({ player: n, cards: game.hands.get(n)?.length || 0 })) }; for (const socket of players.keys()) send(socket, data); }
function sendHand(socket, number) { send(socket, { type: "hand", cards: game.hands.get(number) || [] }); }
function start() { const cards = deck().sort(() => Math.random() - 0.5); game.phase = "sword-choice"; game.sheath = cards.splice(0, 3); game.hands = new Map([[1, []], [2, []], [3, []]]); cards.forEach((card, i) => game.hands.get(i % 3 + 1).push(card)); for (const hand of game.hands.values()) sortHand(hand); game.sheathOwner = [...game.hands].find(([, hand]) => hand.some((card) => card.suit === "♥" && card.rank === "4"))?.[0] || 1; game.turn = game.sheathOwner; for (const [socket, number] of players) sendHand(socket, number); broadcast(); }
function finishSword(number) { game.phase = "playing"; game.hands.get(number).push(...game.sheath); sortHand(game.hands.get(number)); game.sheath = []; game.turn = number; for (const [socket, owner] of players) sendHand(socket, owner); broadcast(); }
function classify(cards) { const v = cards.map((c) => ranks[c.chosenRank || c.rank]).sort((a, b) => a - b); const same = v.every((x) => x === v[0]); if (cards.length === 4 && same) return [5, "star", v[0]]; if (cards.length === 3 && v.join(",") === "4,4,14") return [4, "pierce", 14]; if (cards.length === 3 && same && v[0] === 12) return [3, "cannon", 12]; if (cards.length === 3 && same && v[0] === 6) return [2, "smallCannon", 6]; if (cards.length === 3 && same) return [1, "triple", v[0]]; if (cards.length === 2 && same) return [1, "pair", v[0]]; if (cards.length >= 3 && !v.some((x) => x < 4) && v.every((x, i) => i === 0 || x === v[i - 1] + 1)) return [1, `straight${cards.length}`, v.at(-1)]; if (cards.length === 1) return [1, "single", v[0]]; return null; }
function canBeat(old, next) { return !old || next[0] > old[0] || (next[0] === old[0] && next[1] === old[1] && next[2] > old[2]); }
wss.on("connection", (socket) => { if (players.size === 3) { send(socket, { type: "full" }); socket.close(); return; } const number = players.size + 1; players.set(socket, number); send(socket, { type: "welcome", player: number }); broadcast(); socket.on("message", (raw) => { let msg; try { msg = JSON.parse(raw); } catch { return; } if (msg.type === "ready" && game.phase === "waiting") { game.ready.add(number); broadcast(); if (players.size === 3 && game.ready.size === 3) start(); return; } if (msg.type === "sword" && game.phase === "sword-choice" && game.turn === number) { if (msg.accept) finishSword(number); else { const next = [1, 2, 3].find((n) => !game.ready.has(n) && n !== number); game.ready.add(number); if (next) game.turn = next; else finishSword(game.sheathOwner); broadcast(); } return; } if (msg.type !== "play" || game.phase !== "playing" || game.turn !== number) return; const hand = game.hands.get(number); const indexes = [...new Set(msg.indexes || [])].sort((a, b) => a - b); if (!indexes.length || indexes.some((i) => !hand[i])) return; const selected = indexes.map((i) => ({ ...hand[i] })); if (selected.some((c) => c.joker)) { if (!msg.jokerRank) return; selected.forEach((c) => { if (c.joker) c.chosenRank = msg.jokerRank; }); } const combo = classify(selected); if (!combo || !canBeat(game.lastPlay, combo)) return; indexes.reverse().forEach((i) => hand.splice(i, 1)); game.lastPlay = combo; game.turn = number % 3 + 1; sortHand(hand); for (const [client, owner] of players) sendHand(client, owner); broadcast(); }); socket.on("close", () => { players.delete(socket); reset(); broadcast(); }); });
server.listen(Number(process.env.PORT) || 3000, "0.0.0.0", () => console.log("Card game server running"));
